```{r}
library(TSA)
```


3d
```{r}
set.seed(0144)
require(astsa)
require(forecast)
ma2 = arima.sim(list(order=c(0,0,2), ma=c(.1,-.02)), n = 200) #This simulates an AR(2) model with our chosen coefficients for 200 iterations.
plot(ma2, axes=FALSE, xlab="Time", ylab=expression(X[t]), main="MA(2) Model") #This plots the MA(2) model.
axis(2); axis(1, at=seq(0,200,by=10)); box()
```

3e
```{r}
ACF = ARMAacf(ar=0, ma=c(.1,-0.02), 15)[-1] #ACF with coefficients of the model
PACF = ARMAacf(ar=0, ma=c(0.1,-0.02), 15, pacf=TRUE) #PACF with coefficients of the model
par(mfrow=c(1,2))
plot(ACF, type="h", xlab="lag", ylim=c(-.3,.3)); abline(h=0)
plot(PACF, type="h", xlab="lag", ylim=c(-.3,.3)); abline(h=0)
```

5c

```{r}
set.seed(0144)
require(astsa)
ar2 = arima.sim(list(order=c(2,0,0), ar=c(-.6, .05)), n = 200) #This simulates an AR(2) model with our chosen coefficients for 200 iterations.
plot(ar2, axes=FALSE, xlab="Time", ylab=expression(X[t]), main="AR(2) Model") #This plots the AR(2) model.
axis(2); axis(1, at=seq(0,200,by=10)); box()
```

5d
```{r}
ACF = ARMAacf(ar=c(-.6,.05), ma=0, 15)[-1] #ACF with coefficients of the model
PACF = ARMAacf(ar=c(-.6,.05), ma=0, 15, pacf=TRUE) #PACF with coefficients of the model
par(mfrow=c(1,2))
plot(ACF, type="h", xlab="lag", ylim=c(-.8,1)); abline(h=0)
plot(PACF, type="h", xlab="lag", ylim=c(-.8,1)); abline(h=0)
```

5e
```{r, fig.height = 5, fig.width = 10}
set.seed(0144)
x1=arima.sim(list(order = c(2, 0,0), ar=c(-.6, .05)),n=1000)

ar(x1,order.max=2,aic=F,method='yw') # method of moments
ar(x1,order.max=2,aic=F,method='ols') # conditional sum of squares
ar(x1,order.max=2,aic=F,method='mle') # maximum likelihood
```

6b
```{r}
set.seed(0144)
x5=arima.sim(list(order = c(2, 0, 1),ar = c(.2, -.08), ma = c(.5)),n=1200)

ar(x5,order.max=2,aic=F,method='yw') # method of moments
ar(x5,order.max=2,aic=F,method='ols') # conditional sum of squares
ar(x5,order.max=2,aic=F,method='mle') # maximum likelihood
```

7b
```{r}
data(robot)
model = arima(robot, order=c(1, 0, 1))
plot(model, n1 = 300, n.ahead = 5, ylab = 'Deviation', pch = 19)
```

8a
```{r}
require(forecast)
set.seed(0144)
timeseries=arima.sim(list(order = c(2,1,1), ma=.8, ar=c(1.5, -0.75)), n = 140)
plot(timeseries, axes = FALSE, xlab= "Time", ylab = expression(X[t]), main = "ARIMA(2, 1, 1) Model")
axis(2); axis(1, at=seq(0,140, by=10)); box()
fc = forecast(timeseries, h=10)
plot(fc, main = "Forecast for ARIMA(2, 1, 1) Model")
axis(2); axis(1, at = seq(0, 150, by = 10)); box()

```


9a
```{r}
data(hare)
BoxCox.ar(sqrt(hare))
```

9b
```{r}
mean(sqrt(hare))
var(sqrt(hare))
```

9c
```{r}
ar(sqrt(hare),order.max=2,aic=F,method='yw')
```

10a
```{r}
set.seed(0144)
phi=c(rep(0,11),0.5)
sAR=arima.sim(list(order=c(12,0,0),ar=phi),n=37)
sAR=ts(sAR,freq=12)
layout(matrix(c(1,2,1,3),nc=2))
par(mar=c(3,3,2,1),mgp=c(1.6,0.6,0))
plot(sAR, axes=F, main='Seasonal AR(1)', xlab='year',type='c')
Months=c('J','F','M','A','M','J','J','A','S','O','N','D')
points(sAR, pch=Months, cex=1.25,font=4,col=1:4)

axis(1,1:4);abline(v=1:4,lty=2,col=gray(0.6))
axis(2); box()

# Plotting the TRUE ACF and PACF for this model:
ACF=ARMAacf(ar=phi,ma=0,100)
PACF=ARMAacf(ar=phi,ma=0,100,pacf=T)
plot(ACF,type='h',xaxp = c(0, 96, 8),xlab='lag',ylim=c(-.1,1))
abline(h=0)

#axis(1,at=c(0,12,24,36,48,60,72,84,96),labels=c(NA,12,24,36,48,60,72,84,96))
plot(PACF,type='h',xaxp = c(0, 96, 8),xlab='lag',ylim=c(-.1,1))
abline(h=0)
```


10b
```{r}
phi = c(rep(0,11),.6)
ACF = ARMAacf(ar=phi, ma=-.3, 50)[-1] # [-1] removes 0 lag
PACF = ARMAacf(ar=phi, ma=-.3, 50, pacf=TRUE)
par(mfrow=c(1,2))
plot(ACF, type="h",xaxp = c(0, 48, 4), xlab="LAG", ylim=c(-.4,.8)); abline(h=0)
plot(PACF, type="h", xaxp = c(0, 48, 4),xlab="LAG", ylim=c(-.4,.8)); abline(h=0)
```
